name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    # As of 05/2025, ubuntu-22.04-arm, ubuntu-24.04-arm and windows-11-arm are not supported yet for private repositories
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git qemu-user-static debootstrap kpartx dosfstools debhelper devscripts build-essential rpi-make-boot-image

      - name: Run build.sh
        run: sh -ex ./build.sh
